# before editing this file, copy it to
# config.toml, since this is an example
# file NOT read by the program

password = "" # enter your mun password here
username = "" # enter your mun username here

term = "" # enter the term here, for example, for fall 2022, enter in "202201"

[notification]
[notification.twillio]
account_sid = "" # twillio account sid
auth_token = "" # twillio auth_token
number_to_text = "" # number to text

[[course]]
number = "" # enter course number here, like 2001
subject = "" # enter subject here, like COMP

[[course]] # include as many of these as you want to check
number = ""
subject = ""
